#!/usr/bin/env bash
# vim: set filetype=sh
#
# Launch IDE configuration editing session
#
# Author: Daniil Bargman (daniil.bargman@gmail.com)

cd ~
[ -f .LastVimSession.vim ] && vim -S .LastVimSession.vim || vim

# done.
