#!/usr/bin/env bash
# vim: set filetype=sh
#
# Launch session for editing auto-executable files, e.g. tmux projects
#
# Author: Daniil Bargman (daniil.bargman@gmail.com)

cd ~/executables
[ -f .LastVimSession.vim ] && vim -S .LastVimSession.vim || vim

# done.
