#!/usr/bin/env bash
# vim: set filetype=sh :
#
# s3 synchronization command for all contents of this directory.
#
# Author: Daniil Bargman (daniil.bargman@gmail.com)
#
# base directory of this file accounting for symlinks
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until file is no longer a symlink
    BASE_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
done
BASE_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
[ -z "${SCRIPT_NAME:-}" ] && export SCRIPT_NAME="${0##*/}"
###############################################################################

# error-safe script settings
set -Eeuo pipefail

# default message appendix on errors
function append_error {
    bl=${BASH_LINENO[$((${#BASH_LINENO[@]} - 2))]}
    echo line $bl in $BASE_DIR/$SCRIPT_NAME
    exit 1
}

# trap errors from third-party functions
trap append_error ERR

# manual error handler: refer to help flag, and exit (use in place of echo)
function error_exit {
    echo
    echo $1
    append_error
}

# temporarily save s3cfg file to script's directory
cfg=/tmp/daniilbargman-backups.s3cfg
pass show private/S3/daniilbargman-backups.s3cfg > $cfg

# run sync command
s3cmd -c $cfg --recursive --follow-symlinks --delete-removed \
      --exclude="**/.tmp/" --exclude="**/results/" \
      --exclude="**/__pycache__/" \
      sync ~/sync/documents/* "s3://daniilbargman-backups/"

# delete config file
rm $cfg

# Done.
