#!/usr/bin/env bash
# vim: set filetype=sh
#
# Launch session for editing auto-executable files, e.g. tmux projects
#
# Author: Daniil Bargman (daniil.bargman@gmail.com)

# session name and base directory
session="new-tmux-session"
conda_env=
cd ~

# function for h-split window
function hsplit {
    tmux split-window -v -p 20
    tmux send-keys "cd $1" C-m
    [ "$conda_env" = "" ] || tmux send-keys "source activate $conda_env" C-m
    tmux select-pane -U
    tmux send-keys "cd $1" C-m
    [ "$conda_env" = "" ] || tmux send-keys "source activate $conda_env" C-m
    tmux send-keys "sleep 2 && vimsession" C-m
}

# function for h-split window
function vsplit {
    tmux split-window -h
    tmux send-keys "cd $1" C-m
    [ "$conda_env" = "" ] || tmux send-keys "source activate $conda_env" C-m
    tmux select-pane -U
    tmux send-keys "cd $1" C-m
    [ "$conda_env" = "" ] || tmux send-keys "source activate $conda_env" C-m
    tmux send-keys "sleep 2 && vimsession" C-m
}

# set up tmux
tmux start-server

# create a new tmux session, starting vim from a saved session in the new window
tmux new-session -d -s $session

# first window needs "rename"
tmux rename-window "master"
hsplit "./.tmux"

# others can just be created
tmux new-window -t $session -n "hsplit-window"
hsplit "./.executables"
tmux new-window -t $session -n "vsplit-window"
vsplit "./.tmux"

# return to main vim window
tmux select-window -t $session:1

# Finished setup, attach to the tmux session!
tmux attach-session -t $session

# done.
