[font]
size = 7.5

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "A"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "A"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = 7
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "P"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "P"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "~Vi"
mods = "Control|Shift"

[window]
dynamic_title = false
opacity = 0.95

[window.class]
general = "Alacritty"
instance = "Alacritty"

[keyboard]
